apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vmcluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/satoruh/homelab.git
    targetRevision: master
    path: manifests/vmcluster
  destination:
    server: https://kubernetes.default.svc
    namespace: vmcluster
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
