apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- namespace.yaml
- https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.10.6
- application.yaml

patches:
- path: argocd-cm.yaml
- path: argocd-secrets.yaml
