apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- namespace.yaml
- https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.10.6
- application.yaml

patches:
- path: overlays/argocd-cm.yaml
- path: overlays/argocd-secrets.yaml
- target:
    version: v1
    kind: Service
    name: argocd-server
  patch: |-
    - op: add
      path: /spec/type
      value: LoadBalancer
