---
- name: Restart coredns
  become: yes
  systemd:
    name: coredns
    enabled: true
    daemon-reload: true
    state: restarted

- name: Restart etcd
  become: yes
  systemd:
    name: etcd
    enabled: true
    daemon-reload: true
    state: restarted
