apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
spec:
  project: default
  source:
    repoURL: https://victoriametrics.github.io/helm-charts/
    targetRevision: 0.11.15
    chart: victoria-metrics-cluster
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: victoria-metrics
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
