apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contour
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 17.0.7
    chart: contour
  destination:
    server: https://kubernetes.default.svc
    namespace: projectcontour
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
