apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- apps/homelab-apps.yaml
- apps/kube-vip-cloud-controller.yaml
- apps/victoria-metrics-operator.yaml
- apps/victoria-metrics.yaml
- apps/grafana.yaml
- apps/monitoring.yaml
