apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
  namespace: vmagent
spec:
  selectAllByDefault: true
  remoteWrite:
    - url: "http://vminsert-vmcluster.vmcluster.svc.cluster.local:8480/insert/0/prometheus/api/v1/write"
  scrapeInterval: 30s
  replicaCount: 3
