apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: vmcluster
spec:
  retentionPeriod: "12"
  vmstorage:
    replicaCount: 2
    extraArgs:
      dedup.minScrapeInterval: 30s
  vmselect:
    replicaCount: 2
    extraArgs:
      dedup.minScrapeInterval: 30s
  vminsert:
    replicaCount: 2
