apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics-operator
spec:
  project: default
  source:
    repoURL: https://victoriametrics.github.io/helm-charts/
    targetRevision: 0.30.2
    chart: victoria-metrics-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: victoria-metrics-operator
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
