rook-ceph-cluster:
  operatorNamespace: rook-ceph
  cephClusterSpec:
    external:
      enable: true
    crashCollector:
      disable: true
    healthCheck:
      daemonHealth:
        mon:
          disabled: false
          interval: 45s
  cephBlockPools: {}
  cephFileSystems: {}
  cephObjectStores: {}
