apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: grafana
  labels:
    dashboards: grafana
spec:
  service:
    metadata:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: grafana.k01.lab.internal
    spec:
      type: LoadBalancer
  deployment:
    spec:
      strategy:
        type: Recreate
      template:
        spec:
          # https://github.com/grafana/grafana-operator/issues/1439
          securityContext:
            fsGroup: 472
          containers:
          - name: grafana
            securityContext:
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: false
            readinessProbe:
              failureThreshold: 3
          volumes:
          - name: grafana-data
            persistentVolumeClaim:
              claimName: grafana-pvc
  persistentVolumeClaim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 16Gi
