apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: grafana
  labels:
    app.kubernetes.io/name: grafana
  annotations:
    external-dns.alpha.kubernetes.io/hostname: grafana.k01.lab.internal
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-grafana
  selector:
    app.kubernetes.io/name: grafana
  sessionAffinity: None
  type: LoadBalancer
