- hosts: kubernetes_control_planes:kubernetes_workers
  gather_facts: False

  tasks:
  - include_vars:
      file: ../vars.yaml

  - name: Configure network
    become: yes
    block:
      - name: modules
        block:
        - copy:
            dest: /etc/modules-load.d/k8s.conf
            owner: root
            group: root
            mode: '0644'
            content: |-
              overlay
              br_netfilter
        - shell: modprobe overlay
        - shell: modprobe br_netfilter
      - name: sysctl
        block:
        - copy:
            dest: /etc/sysctl.d/k8s.conf
            owner: root
            group: root
            mode: '0644'
            content: |-
              net.bridge.bridge-nf-call-iptables  = 1
              net.bridge.bridge-nf-call-ip6tables = 1
              net.ipv4.ip_forward                 = 1
        - shell: sysctl --system

  - name: Install a container runtime
    become: yes
    block:
    - name: Add docker repository
      block:
      - get_url:
          url: "https://download.docker.com/linux/ubuntu/gpg"
          dest: /etc/apt/keyrings/docker.asc
      - apt_repository:
          repo: "deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu jammy stable"
    - name: Install containerd.io
      apt:
        name:
        - containerd.io
    - name: Configure cgroup driver
      shell: |-
        set -euo pipefail
        containerd config default |
          sed -e 's/SystemdCgroup = false/SystemdCgroup = true/' > /etc/containerd/config.toml
    - name: Restart containerd
      systemd:
        name: containerd
        state: restarted

  - name: Install kubeadm, kubelet and kubectl
    become: yes
    block:
      - name: Add Kubernetes repository
        block:
        - get_url:
            url: "https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/Release.key"
            dest: /etc/apt/keyrings/kubernetes.asc
        - apt_repository:
            repo: "deb [signed-by=/etc/apt/keyrings/kubernetes.asc] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/ /"
      - name: Install and hold packages
        block:
        - name: Install packages
          apt:
            name:
              - kubeadm
              - kubelet
              - kubectl
        - name: Hold packages
          dpkg_selections:
            selection: hold
            name: "{{ item }}"
          with_items:
            - kubeadm
            - kubelet
            - kubectl
        - name: Start kubelet
          systemd:
            name: kubelet
            state: restarted
            enabled: yes
