- hosts: kubernetes_control_planes:kubernetes_workers
  gather_facts: False

  tasks:
  - include_vars:
      file: ../vars.yaml

  - name: kubernetes-node-base
    import_role:
      name: kubernetes-node-base
    vars:
      kubernetes_version: "{{ kubernetes_version }}"
