kubernetes_cluster_name: k01
kubernetes_version: 1.29
calico_version: 3.27.3
kube_vip_version: 0.8.0

authorized_keys:
- ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICyAkItUqKGajTGSFKrGvJHL+Da5vOVG3Xd5Sj7UUAhK

proxmox_resource_pool: k01
proxmox_storage: k01
image_url: https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-amd64-disk-kvm.img

kubernetes_node_default: &kubernetes_node_default
  disksize: 8G

kubernetes_control_plane_default: &kubernetes_control_plane_default
  <<: *kubernetes_node_default
  cores: 2
  memory: 2048
  bridge: vmbr0
  vlan: 3841
  gateway: 10.15.1.1
  nameserver: 10.15.0.1

kubernetes_worker_default: &kubernetes_worker_default
  <<: *kubernetes_node_default
  cores: 2
  memory: 2048
  bridge: vmbr0
  vlan: 3842
  gateway: 10.15.2.1
  nameserver: 10.15.0.1

kubernetes_control_planes: &kubernetes_control_planes
- <<: *kubernetes_control_plane_default
  id: 10011
  hostname: k01c01
  ip: 10.15.1.11/24
- <<: *kubernetes_control_plane_default
  id: 10012
  hostname: k01c02
  ip: 10.15.1.12/24
- <<: *kubernetes_control_plane_default
  id: 10013
  hostname: k01c03
  ip: 10.15.1.13/24

kubernetes_workers: &kubernetes_workers
- <<: *kubernetes_worker_default
  id: 11011
  hostname: k01w01
  ip: 10.15.2.11/24
- <<: *kubernetes_worker_default
  id: 11012
  hostname: k01w02
  ip: 10.15.2.12/24
- <<: *kubernetes_worker_default
  id: 11013
  hostname: k01w03
  ip: 10.15.2.13/24

kubernetes_nodes:
- *kubernetes_control_planes
- *kubernetes_workers

kube_vip_image: "ghcr.io/kube-vip/kube-vip:v{{kube_vip_version}}"
kube_vip_localas: "65000"
kube_vip_peer_address: 10.15.1.1

control_plane_endpoint_addr: 10.15.1.10
control_plane_endpoint_port: 6443
pod_network_cidr: 10.239.0.0/16
service_cidr: 10.240.0.0/12
