apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics-operator
spec:
  project: default
  source:
    repoURL: https://github.com/satoruh/homelab.git
    targetRevision: master
    path: manifests/victoria-metrics-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: vm
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
