apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  project: default
  source:
    repoURL: https://github.com/satoruh/homelab.git
    targetRevision: master
    path: kubernetes/manifests/grafana
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
